Implementation of Python Basic Libraries such as Statistics, Math, Numpy and Scipy

Usage of methods such as floor(), ceil(), sqrt(), isqrt(), gcd() etc

In [ ]:
import math

In [ ]:
print(math.ceil(5.3))
print(math.floor(5.4))
print(math.sqrt(16))
print(math.isqrt(167))
print(math.gcd(12,8))

6
5
4.0
12
4

Usage of attributes of array such as ndim, shape, size, methods such as sum(), mean(), sort(), sin() etc.

In [ ]:
import numpy as np
arr = np.array([[1,2,3],[6,5,4]])
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.sum())
print(arr.mean())
print(np.sort(arr))
print("Sine values of each number of the array are \n",np.sin(arr))

2
(2, 3)
6
21
3.5
[[1 2 3]
 [4 5 6]]
Sine values of each number of the array are
 [[ 0.84147098  0.90929743  0.14112001]
 [-0.2794155  -0.95892427 -0.7568025 ]]

Usage of methods such as det(), eig() etc

In [ ]:
matrix = np.array([[1,2,4],[9,7,5],[3,4,5]])
print("Determinant of the matrix is ",np.linalg.det(matrix))
eigenvalues,eigenvectors = np.linalg.eig(matrix)
print("Eigen values are ",eigenvalues)
print("Eigen vectors are \n",eigenvectors)

Determinant of the matrix is  15.000000000000007
Eigen values are  [13.31006364+0.j         -0.15503182+1.05020567j -0.15503182-1.05020567j]
Eigen vectors are
 [[ 0.29449496+0.j          0.4552434 -0.18921254j  0.4552434 +0.18921254j]
 [ 0.81520628+0.j         -0.79232647+0.j         -0.79232647-0.j        ]
 [ 0.49870978+0.j          0.3143861 +0.17416143j  0.3143861 -0.17416143j]]

Consider a list datatype(1D) then reshape it into2D, 3D matrix using numpy

In [ ]:
lst = list( range(12))
array = np.array(lst)
arr_2d = array.reshape((3,4))
print("The 1D array into 2D array as \n",arr_2d)
arr_3d = array.reshape((2,2,3))
print("The 1D array into 2D array as \n",arr_3d)

The 1D array into 2D array as
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
The 1D array into 2D array as
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]

Generater and matrices using numpy

In [ ]:
zero_matrix = np.zeros((3,4))
ones_matrix = np.ones((2,2))
identity_matrix = np.eye(3)
random_matrix = np.random.rand(3,3)

print("Zero matrix \n",zero_matrix)
print("One matrix \n",ones_matrix)
print("Identity matrix \n",identity_matrix)
print("Random matrix \n",random_matrix)

Zero matrix
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
One matrix
 [[1. 1.]
 [1. 1.]]
Identity matrix
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Random matrix
 [[0.41513495 0.14294532 0.30567128]
 [0.00403438 0.89173956 0.2712245 ]
 [0.74018911 0.83806621 0.11624046]]

 Find the determinant of a matrix using scipy

In [ ]:
from scipy.linalg import det,eig
mat = np.array([[1, 2],[3, 4]])
determinant = det(mat)
print(determinant)

-2.0

In [ ]:
mat = np.array([[5, 4],
                [1, 2]])
eigenvalues, eigenvectors = eig(mat)

print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [6.+0.j 1.+0.j]
Eigenvectors:
 [[ 0.9701425  -0.70710678]
 [ 0.24253563  0.70710678]]

Implementation of Python Libraries for ML application such as Pandas and Matplotlib.
Create a Series using pandas and display

In [ ]:
import pandas as pd
data = [10,20,30,40]
series = pd.Series(data)
print("Series using pandas\n",series)

Series using pandas
 0    10
1    20
2    30
3    40
dtype: int64

Access the index and the values of our Series

In [ ]:
print("Index:", series.index)
print("Values:", series.values)

Index: RangeIndex(start=0, stop=4, step=1)
Values: [10 20 30 40]

 Compare an array using Numpy with a series using pandas

In [ ]:
arr = np.array([10, 20, 30, 40])
print("NumPy Array:", arr)
print("Pandas Series:", series)

NumPy Array: [10 20 30 40]
Pandas Series: 0    10
1    20
2    30
3    40
dtype: int64

Define Series objects with individual indices

In [ ]:
data = [100,200,300]
indices = ['a','b','c']
customIndexArray = pd.Series(data,index=indices)
print("The array with custom indices \n",customIndexArray)

The array with custom indices
 a    100
b    200
c    300
dtype: int64

 Access single value of a series

In [ ]:
print(customIndexArray['a'])
print(customIndexArray['b'])

100
200

Load datasets in a Data frame variable using

In [ ]:
df = pd.read_csv('data.csv')
print(df.head())
import seaborn as sns
df_iris = sns.load_dataset('iris')
print(df_iris.head())

          Car       Model  Volume  Weight  CO2
0      Toyoty        Aygo    1000     790   99
1  Mitsubishi  Space Star    1200    1160   95
2       Skoda      Citigo    1000     929   95
3        Fiat         500     900     865   90
4        Mini      Cooper    1500    1140  105
   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

Creation and Loading different types of datasets in Python using the required libraries.

Creation using pandas

In [ ]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston']
}

df = pd.DataFrame(data)
print(df)

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston

In [ ]:
df = pd.read_csv('data.csv')
print(df.head())

          Car       Model  Volume  Weight  CO2
0      Toyoty        Aygo    1000     790   99
1  Mitsubishi  Space Star    1200    1160   95
2       Skoda      Citigo    1000     929   95
3        Fiat         500     900     865   90
4        Mini      Cooper    1500    1140  105

In [ ]:
from sklearn.datasets import load_iris
iris = load_iris()
df_features = pd.DataFrame(iris.data,columns=iris.feature_names)
df_target = pd.Series(iris.target, name='species')
df_iris = pd.concat([df_features, df_target], axis=1)
print(df_iris.head())

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

   species
0        0
1        0
2        0
3        0
4        0